run:
  modules-download-mode: readonly

linters:
  disable:
    - exhaustruct
    - paralleltest
    - rowserrcheck
    - testpackage
    - thelper
    - varnamelen
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused
